name: CI/CD Portfolio Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Build and Run Python Ingestor
        run: |
          cd python-ingestor
          docker build -t portfolio-ingestor:latest .
          
          docker run --rm \
            --network database_default \
            -e DB_HOST=portfolio_db \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PASS="${{ secrets.DB_PASS }}" \
            portfolio-ingestor:latest